/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controller.Controller;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Paciente;

/**
 *
 * @author alumno
 */
public class Formulario extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form Formulario
     */
    public int id_paciente=-1;
            
    public Formulario()  {
        initComponents();
        btnguardar.addActionListener(this);
        btnsalir.addActionListener(this);
        btneliminar.addActionListener(this);        
        cargarDatatable();
        btneliminar.setEnabled(false);
        btnEditar.addActionListener(this);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnguardar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        vista = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro de Pacientes"));
        jPanel1.setLayout(null);

        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(67, 50, 70, 16);
        jPanel1.add(txtnombre);
        txtnombre.setBounds(191, 47, 270, 24);

        jLabel3.setText("Direccion");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 90, 100, 16);
        jPanel1.add(txtdireccion);
        txtdireccion.setBounds(191, 82, 270, 24);

        jLabel4.setText("Telefono");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 123, 100, 16);
        jPanel1.add(txttelefono);
        txttelefono.setBounds(191, 120, 270, 24);

        jLabel6.setText("Registro de Pacientes");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(250, 30, 170, 16);

        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anadir.png"))); // NOI18N
        btnguardar.setText("Guardar");
        jPanel1.add(btnguardar);
        btnguardar.setBounds(16, 151, 154, 40);

        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cerrar.png"))); // NOI18N
        btnsalir.setText("Salir");
        jPanel1.add(btnsalir);
        btnsalir.setBounds(469, 151, 125, 41);

        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trash.png"))); // NOI18N
        btneliminar.setText("Elliminar");
        jPanel1.add(btneliminar);
        btneliminar.setBounds(321, 151, 138, 41);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        jPanel1.add(btnEditar);
        btnEditar.setBounds(180, 150, 130, 40);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 650, 220));

        vista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        vista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vistaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(vista);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 610, 130));

        jLabel1.setText("UNIVERSIDAD MARIANO GALVEZ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jLabel5.setText("Vista previa");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vistaMouseClicked
        // TODO add your handling code here:
       
      if (vista.getRowCount() <= 0) {
            JOptionPane.showConfirmDialog(null, "no hay datos para cargar");
        } else {
            this.id_paciente = Integer.parseInt(vista.getValueAt(vista.getSelectedRow(), 0).toString());
            txtnombre.setText(vista.getValueAt(vista.getSelectedRow(), 1).toString());
            txtdireccion.setText(vista.getValueAt(vista.getSelectedRow(), 2).toString());
            txttelefono.setText(vista.getValueAt(vista.getSelectedRow(), 3).toString());
            btneliminar.setEnabled(true);

        }

    }//GEN-LAST:event_vistaMouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttelefono;
    private javax.swing.JTable vista;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == btnguardar) {
            if (validacion(txtnombre.getText()) || (validacion(txttelefono.getText()))) {
                JOptionPane.showMessageDialog(null, "Debe completar el formulario");
                return;
            } else {
                Paciente p = new Paciente();
                p.setNombre(txtnombre.getText());
                p.setDireccion(txtdireccion.getText());
                p.setTelefono(txttelefono.getText());
                Controller c = new Controller();
                try {
                    c.Guardar(p);
                    JOptionPane.showMessageDialog(null, "Registro creado correctamente");
                    this.cargarDatatable();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Registro no fue realizado por" + ex.getMessage());
                }

            }

        }
        if (e.getSource() == btnsalir) {
            System.exit(0);
        }
        if (e.getSource() == btneliminar) {
            if (this.id_paciente != -1) {
                Controller c = new Controller();
                if (c.Eliminar(this.id_paciente)) {
                    cargarDatatable();
                    JOptionPane.showMessageDialog(null, "Registro eliminado con exito!!!");
                } else {
                    JOptionPane.showMessageDialog(null, "No fue posible eliminar el registro!!!");

                }

            }
        }
        if(e.getSource()==btnEditar)
        {
            if (this.id_paciente != -1) {            
                   Controller c = new Controller();
                   Paciente p = new Paciente();
                   p.setNombre(txtnombre.getText());
                   p.setDireccion(txtdireccion.getText());
                 p.setTelefono(txttelefono.getText());
                if (c.Editar(p, this.id_paciente)) {
                    cargarDatatable();
                    JOptionPane.showMessageDialog(null, "Registro actualizado con exito!!!");
                } else {
                    JOptionPane.showMessageDialog(null, "No fue posible actualizar el registro!!!");

                } 
                   
            }
            else{
                
                JOptionPane.showMessageDialog(null,"No hay datos para editar");
            }
                                    
            
        }
    }

    public void cargarDatatable() {
        DefaultTableModel model = new DefaultTableModel();
        Controller c = new Controller();
        try {
            c.Consultar(model);
            vista.setModel(model);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "error al cargar los datos por :  " + ex.getMessage());
        }

    }


   public boolean validacion(String texto)
   {
      boolean res = false;      
       if (texto.isEmpty()) {
           return true;
       }
       return res;
   }
}
